baseURL = "http://das-snigdha.github.io/"
languageCode = "en-us"
title = "Snigdha Das"
theme = "barks"

[params.head]
author = "Snigdha Das"
description = "Statistics • Bayesian • Teaching"
keywords = ["statistics","bayesian","teaching"]

[params.navigation]
show_navigation = true

[params.footer]
show_footer = true

[params.typography]
title_font = "Bree Serif"
body_font  = "Source Sans Pro"

[params.colors]
theme_color      = "#333333"
background_color = "#fcfbf9"
text_color       = "#333333"
link_color       = "#800000"
